<?php

namespace Rwmt\Bundle\RwmtBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
/**
 * RideToUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RideToUserRepository extends EntityRepository
{
    
}
