rwmtRegistrationAPI:
  type: rest
  prefix: /api/v1
  resource: @RwmtBundle/Controller/ApiRegistrationController.php

rwmtRidesAPI:
  type: rest
  prefix: /api/v1
  resource: @RwmtBundle/Controller/ApiRidesController.php

rwmtCarsAPI:
  type: rest
  prefix: /api/v1
  resource: @RwmtBundle/Controller/ApiCarsController.php

rwmtUserRidesAPI:
  type: rest
  prefix: /api/v1
  resource: @RwmtBundle/Controller/ApiUserController.php


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/v1/doc

logout:
    path:   /api/v1/logout