parameters:
#    rwmt.example.class: Rwmt\Bundle\RwmtBundle\Example

services:
#    app.filter_manager:
#            class: Rwmt\Bundle\RwmtBundle\Services\DoctrineSqlFilterConfigurator
#            arguments: [@doctrine.orm.entity_manager]
#            tags:
#                - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
